// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMFE3zxuMrz06xHAq3xwspsGe7BZSDm8',
    appId: '1:940047034816:web:38280c3994a5168133c025',
    messagingSenderId: '940047034816',
    projectId: 'note-app-firebase-33ca3',
    authDomain: 'note-app-firebase-33ca3.firebaseapp.com',
    storageBucket: 'note-app-firebase-33ca3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1l_Rj34wz35mIzYI5i4m4IxXZ6vrvNY',
    appId: '1:940047034816:android:652bbd280f37693833c025',
    messagingSenderId: '940047034816',
    projectId: 'note-app-firebase-33ca3',
    storageBucket: 'note-app-firebase-33ca3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACB3Exr9VzDMRbOA25nifnz2hDzzjQnTE',
    appId: '1:940047034816:ios:7b483cac6fe5fb5a33c025',
    messagingSenderId: '940047034816',
    projectId: 'note-app-firebase-33ca3',
    storageBucket: 'note-app-firebase-33ca3.firebasestorage.app',
    iosBundleId: 'com.example.noteAppWithFirebase',
  );
}
